#!/usr/bin/env bash
##############################################################################
# tests/test-personas-post-splice.sh
#
# pipeline-gate-permissiveness W3.2b — independent post-splice validator.
#
# Catches failure modes that test-class-tagging-spliced.sh's sentinel-only
# checks would miss (per /check risk M1):
#   - Splicer corrupted the persona's h1 title
#   - Splice landed mid-section (e.g., inside a list, breaking the parent)
#   - Sentinel pair integrity (every BEGIN has matching END, in order)
#   - Duplicate BEGIN sentinels (idempotency violation)
#   - Persona file shrunk impossibly (less than 20 lines = something was eaten)
#
# Independence: this test is hand-written (not auto-generated by the splice
# script) and asserts STRUCTURAL invariants, not template-content equality.
# A splice-script bug + same-author content test would not catch corruption
# of the persona's own pre-existing content; this test does.
##############################################################################
set -uo pipefail

ENGINE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PERSONAS_DIR="$ENGINE_DIR/personas"

PASS=0
FAIL=0

note_pass() { echo "  PASS — $1"; PASS=$(( PASS + 1 )); }
note_fail() { echo "  FAIL — $1"; FAIL=$(( FAIL + 1 )); }

# Discover persona files under review/, plan/, check/ (the splice targets).
shopt -s nullglob
personas=()
for sub in review plan check; do
  for f in "$PERSONAS_DIR/$sub"/*.md; do
    personas+=("$f")
  done
done
shopt -u nullglob

if [ "${#personas[@]}" -eq 0 ]; then
  echo "✗ no personas found under $PERSONAS_DIR/{review,plan,check}/"
  exit 1
fi

echo "Scanning ${#personas[@]} personas for post-splice structural integrity..."

for f in "${personas[@]}"; do
  rel="${f#$ENGINE_DIR/}"

  # Invariant 1: file has at least 20 lines (smallest persona is ~30 lines pre-splice;
  # post-splice should be ~80+ lines). Anything tiny is a likely truncation.
  lines="$(wc -l < "$f" | tr -d ' ')"
  if [ "$lines" -lt 20 ]; then
    note_fail "$rel — only $lines lines (probable truncation)"
    continue
  fi

  # Invariant 2: first non-blank line is an h1 (persona title preserved).
  first_line="$(awk 'NF { print; exit }' "$f")"
  case "$first_line" in
    \#\ *) ;;  # h1 ok
    *) note_fail "$rel — first non-blank line is not an h1 title: '$first_line'"; continue ;;
  esac

  # Invariant 3: BEGIN/END sentinel pair integrity.
  begin_count="$(grep -c '^<!-- BEGIN class-tagging -->$' "$f" || true)"
  end_count="$(grep -c '^<!-- END class-tagging -->$' "$f" || true)"

  if [ "${begin_count:-0}" -gt 1 ]; then
    note_fail "$rel — duplicate BEGIN class-tagging sentinels (n=$begin_count)"
    continue
  fi

  if [ "${end_count:-0}" -gt 1 ]; then
    note_fail "$rel — duplicate END class-tagging sentinels (n=$end_count)"
    continue
  fi

  if [ "${begin_count:-0}" -ne "${end_count:-0}" ]; then
    note_fail "$rel — sentinel pair mismatch (BEGIN=$begin_count, END=$end_count)"
    continue
  fi

  # Invariant 4: if BEGIN exists, END appears AFTER it (not before).
  if [ "${begin_count:-0}" -eq 1 ]; then
    begin_line="$(grep -n '^<!-- BEGIN class-tagging -->$' "$f" | cut -d: -f1)"
    end_line="$(grep -n '^<!-- END class-tagging -->$' "$f" | cut -d: -f1)"
    if [ "${begin_line:-0}" -ge "${end_line:-0}" ]; then
      note_fail "$rel — END sentinel appears at/before BEGIN (BEGIN line $begin_line, END line $end_line)"
      continue
    fi
  fi

  note_pass "$rel — $lines lines, sentinels OK"
done

echo ""
echo "================================================="
echo "Results: $PASS passed, $FAIL failed"

if [ "$FAIL" -gt 0 ]; then
  exit 1
fi
exit 0
