// judge.js — renders the Judge tab from window.__JUDGE_DATA
// (set by judge-bundle.js, regenerated by scripts/judge-dashboard-bundle.sh).
//
// Each card has a small "Reads:" footer naming the on-disk path it pulls from,
// so the dashboard is its own documentation: hover any chart and you can find
// the source jsonl yourself.

const judgeState = {
  projects: {},        // slug -> { path, features: {feature: {stages: {...}}} }
  generatedAt: null,
  active: "__all",
  charts: {},
  loaded: false,
};

function loadJudgeBundle() {
  const bundle = window.__JUDGE_DATA;
  if (!bundle || typeof bundle !== "object") {
    return false;
  }
  judgeState.projects = bundle.projects || {};
  judgeState.generatedAt = bundle.generated_at || null;
  judgeState.loaded = true;
  return true;
}

function destroyJudgeCharts() {
  for (const c of Object.values(judgeState.charts)) {
    try { c.destroy(); } catch {}
  }
  judgeState.charts = {};
}

function renderJudgeTabs() {
  const tabs = document.getElementById("tabs");
  tabs.innerHTML = "";
  const all = document.createElement("button");
  all.textContent = "All projects";
  all.dataset.project = "__all";
  if (judgeState.active === "__all") all.classList.add("active");
  all.onclick = () => setJudgeActive("__all");
  tabs.appendChild(all);
  for (const slug of Object.keys(judgeState.projects).sort()) {
    const b = document.createElement("button");
    b.textContent = slug;
    b.dataset.project = slug;
    if (judgeState.active === slug) b.classList.add("active");
    b.onclick = () => setJudgeActive(slug);
    tabs.appendChild(b);
  }
}

function setJudgeActive(slug) {
  judgeState.active = slug;
  document.querySelectorAll("#tabs button").forEach(b => {
    b.classList.toggle("active", b.dataset.project === slug);
  });
  renderJudgeMain();
}

function flatStages() {
  // Flatten { proj: { features: { feat: { stages: { stage: blob } } } } }
  // into [{ project, feature, stage, ...blob }]
  const out = [];
  const projects = judgeState.active === "__all"
    ? judgeState.projects
    : { [judgeState.active]: judgeState.projects[judgeState.active] };
  for (const [proj, p] of Object.entries(projects || {})) {
    if (!p || !p.features) continue;
    for (const [feat, f] of Object.entries(p.features)) {
      for (const [stage, blob] of Object.entries(f.stages || {})) {
        out.push({ project: proj, feature: feat, stage, ...blob });
      }
    }
  }
  return out;
}

function verdictBadgeClass(v) {
  if (!v) return "yellow";
  const u = v.toUpperCase();
  if (u === "GO" || u === "PASS") return "green";
  if (u === "NO-GO" || u === "FAIL") return "red";
  return "yellow";
}

function renderJudgeMain() {
  destroyJudgeCharts();
  const main = document.getElementById("main");
  main.innerHTML = "";
  const rows = flatStages();

  // Always-show: the "About" card. Self-documenting entry point.
  addAboutCard(main);

  if (!rows.length) {
    main.insertAdjacentHTML(
      "beforeend",
      `<div class="card wide"><div class="empty">
        No judge data found yet. Run <code>/spec-review</code>, <code>/plan</code>,
        or <code>/check</code> on a feature in <code>docs/specs/&lt;feature&gt;/</code>,
        then <code>bash ~/Projects/MonsterFlow/scripts/judge-dashboard-bundle.sh</code>.
       </div></div>`
    );
    return;
  }

  addVerdictTable(main, rows);
  addCompressionCard(main, rows);
  addPersonaContributionCard(main, rows);
  addSurvivalCard(main, rows);
  addDisagreementsCard(main, rows);
  addRecentFindingsCard(main, rows);
}

function addAboutCard(main) {
  const card = document.createElement("div");
  card.className = "card wide";
  card.innerHTML = `
    <h2>About the Judge view</h2>
    <p style="margin:0 0 8px 0;">
      Each <code>/spec-review</code>, <code>/plan</code>, and <code>/check</code> gate
      runs multiple specialist agents in parallel, then a Judge persona
      (<code>personas/judge.md</code>) deduplicates and resolves conflicts before
      Synthesis writes the final artifact. This view shows what Judge is doing
      across all projects under <code>~/Projects/*/docs/specs/</code>.
    </p>
    <p style="margin:0 0 8px 0;color:var(--muted);font-size:12px;">
      Reads (per feature, per stage): <code>findings.jsonl</code>,
      <code>participation.jsonl</code>, <code>run.json</code>,
      <code>survival.jsonl</code>, <code>raw/*.md</code>, and the synthesized
      <code>&lt;stage&gt;.md</code>. Bundle regenerated by
      <code>scripts/judge-dashboard-bundle.sh</code>.
    </p>
    <p style="margin:0;color:var(--muted);font-size:12px;">
      Bundle generated: ${judgeState.generatedAt || "unknown"}.
    </p>
  `;
  main.appendChild(card);
}

function addVerdictTable(main, rows) {
  const card = document.createElement("div");
  card.className = "card wide";
  card.innerHTML = `<h2>Recent gates · verdict</h2>
    <table><thead><tr>
      <th>Project</th><th>Feature</th><th>Stage</th><th>Verdict</th>
      <th>Findings</th><th>Raw → clusters</th><th>Disagreements</th>
      <th>When</th><th>Open</th>
    </tr></thead><tbody></tbody></table>
    <p style="margin:8px 0 0 0;color:var(--muted);font-size:11px;">
      Reads: <code>docs/specs/&lt;feature&gt;/&lt;stage&gt;.md</code> +
      <code>findings.jsonl</code>. Verdict is parsed from prose — null = couldn't
      detect a recognized verdict line.
    </p>`;
  main.appendChild(card);
  const tbody = card.querySelector("tbody");
  const sorted = [...rows].sort((a, b) =>
    (b.timestamp || "").localeCompare(a.timestamp || ""));
  for (const r of sorted.slice(0, 40)) {
    const v = r.verdict || "—";
    const badge = verdictBadgeClass(r.verdict);
    const compress = r.raw_finding_count
      ? `${r.raw_finding_count} → ${r.findings.length}`
      : `— → ${r.findings.length}`;
    const when = r.timestamp ? formatJudgeTs(r.timestamp) : "—";
    const openLink = r.synth_path
      ? `<a href="file://${r.synth_path}">md</a>`
      : "—";
    tbody.insertAdjacentHTML("beforeend", `
      <tr>
        <td>${r.project}</td>
        <td>${r.feature}</td>
        <td>${r.stage}</td>
        <td><span class="badge ${badge}">${v}</span></td>
        <td>${r.findings.length}</td>
        <td>${compress}</td>
        <td>${r.disagreements}</td>
        <td>${when}</td>
        <td>${openLink}</td>
      </tr>`);
  }
}

function addCompressionCard(main, rows) {
  const card = document.createElement("div");
  card.className = "card";
  card.innerHTML = `<h2>Judge compression: raw bullets → final clusters</h2>
    <canvas id="judge-chart-compression"></canvas>
    <p style="margin:8px 0 0 0;color:var(--muted);font-size:11px;">
      Reads: line counts in <code>&lt;stage&gt;/raw/*.md</code> vs
      rows in <code>&lt;stage&gt;/findings.jsonl</code>. Higher gap = Judge
      removed more noise.
    </p>`;
  main.appendChild(card);
  const labels = rows.map(r => `${r.project}/${r.feature.slice(0, 18)}/${r.stage}`);
  const raw = rows.map(r => r.raw_finding_count || 0);
  const final = rows.map(r => r.findings.length);
  judgeState.charts.compression = new Chart(
    card.querySelector("canvas").getContext("2d"),
    {
      type: "bar",
      data: {
        labels,
        datasets: [
          { label: "raw bullets", data: raw, backgroundColor: "#e5c07b" },
          { label: "final clusters", data: final, backgroundColor: "#4ec9b0" },
        ],
      },
      options: {
        responsive: true, animation: false,
        plugins: { legend: { labels: { color: "#9aa0a6" } } },
        scales: {
          x: { ticks: { color: "#9aa0a6", maxRotation: 60, minRotation: 30 },
               grid: { color: "#262a33" } },
          y: { ticks: { color: "#9aa0a6" }, grid: { color: "#262a33" },
               beginAtZero: true },
        },
      },
    }
  );
}

function addPersonaContributionCard(main, rows) {
  const card = document.createElement("div");
  card.className = "card";
  card.innerHTML = `<h2>Persona contribution (clusters touched)</h2>
    <canvas id="judge-chart-personas"></canvas>
    <p style="margin:8px 0 0 0;color:var(--muted);font-size:11px;">
      Reads: <code>&lt;stage&gt;/findings.jsonl</code> · <code>personas[]</code>.
      A persona that appears on many post-Judge clusters is doing real work;
      one that's flat may be getting demoted.
    </p>`;
  main.appendChild(card);
  const counts = {};
  for (const r of rows) {
    for (const f of r.findings) {
      for (const p of (f.personas || [])) {
        counts[p] = (counts[p] || 0) + 1;
      }
    }
  }
  const entries = Object.entries(counts).sort((a, b) => b[1] - a[1]);
  judgeState.charts.personas = new Chart(
    card.querySelector("canvas").getContext("2d"),
    {
      type: "bar",
      data: {
        labels: entries.map(e => e[0]),
        datasets: [{ label: "clusters", data: entries.map(e => e[1]),
                     backgroundColor: "#4ec9b0" }],
      },
      options: {
        indexAxis: "y",
        responsive: true, animation: false,
        plugins: { legend: { display: false } },
        scales: {
          x: { ticks: { color: "#9aa0a6" }, grid: { color: "#262a33" },
               beginAtZero: true },
          y: { ticks: { color: "#9aa0a6" }, grid: { color: "#262a33" } },
        },
      },
    }
  );
}

function addSurvivalCard(main, rows) {
  const card = document.createElement("div");
  card.className = "card";
  card.innerHTML = `<h2>Survival into next stage (check only)</h2>
    <div id="judge-survival-body"></div>
    <p style="margin:8px 0 0 0;color:var(--muted);font-size:11px;">
      Reads: <code>&lt;feature&gt;/check/survival.jsonl</code>. Tracks how many
      <code>/spec-review</code> and <code>/plan</code> findings survived into
      <code>plan.md</code> / <code>check.md</code>.
    </p>`;
  main.appendChild(card);
  const body = card.querySelector("#judge-survival-body");
  const checks = rows.filter(r => r.stage === "check" && (r.survival || []).length);
  if (!checks.length) {
    body.innerHTML = `<div class="empty">No survival.jsonl emitted yet
      (requires the Persona Metrics survival classifier to have run on /check).</div>`;
    return;
  }
  let html = `<table><thead><tr>
    <th>Project</th><th>Feature</th><th>Tracked</th><th>Survived</th><th>Rate</th>
    </tr></thead><tbody>`;
  for (const c of checks) {
    const total = c.survival.length;
    const survived = c.survival.filter(s => s.survived === true || s.outcome === "survived").length;
    const rate = total ? ((survived / total) * 100).toFixed(0) : "—";
    html += `<tr><td>${c.project}</td><td>${c.feature}</td>
      <td>${total}</td><td>${survived}</td><td>${rate}%</td></tr>`;
  }
  html += "</tbody></table>";
  body.innerHTML = html;
}

function addDisagreementsCard(main, rows) {
  const card = document.createElement("div");
  card.className = "card";
  card.innerHTML = `<h2>Agent disagreements resolved</h2>
    <canvas id="judge-chart-disagree"></canvas>
    <p style="margin:8px 0 0 0;color:var(--muted);font-size:11px;">
      Reads: bullet count under "Agent Disagreements Resolved" in
      <code>&lt;stage&gt;.md</code>. Strongest signal that Judge actually fired —
      zeros across the board mean Judge is being skipped or had nothing to merge.
    </p>`;
  main.appendChild(card);
  const labels = rows.map(r => `${r.project.slice(0, 8)}/${r.stage}`);
  const data = rows.map(r => r.disagreements || 0);
  judgeState.charts.disagree = new Chart(
    card.querySelector("canvas").getContext("2d"),
    {
      type: "bar",
      data: { labels, datasets: [{ label: "disagreements",
                                   data, backgroundColor: "#e06c75" }] },
      options: {
        responsive: true, animation: false,
        plugins: { legend: { display: false } },
        scales: {
          x: { ticks: { color: "#9aa0a6", maxRotation: 60, minRotation: 30 },
               grid: { color: "#262a33" } },
          y: { ticks: { color: "#9aa0a6" }, grid: { color: "#262a33" },
               beginAtZero: true },
        },
      },
    }
  );
}

function addRecentFindingsCard(main, rows) {
  const card = document.createElement("div");
  card.className = "card wide";
  card.innerHTML = `<h2>Recent blockers</h2>
    <table><thead><tr>
      <th>Project</th><th>Feature</th><th>Stage</th><th>Title</th>
      <th>Personas</th>
    </tr></thead><tbody></tbody></table>
    <p style="margin:8px 0 0 0;color:var(--muted);font-size:11px;">
      Reads: <code>&lt;stage&gt;/findings.jsonl</code> filtered to
      <code>severity == "blocker"</code>.
    </p>`;
  main.appendChild(card);
  const tbody = card.querySelector("tbody");
  const sorted = [...rows].sort((a, b) =>
    (b.timestamp || "").localeCompare(a.timestamp || ""));
  let count = 0;
  for (const r of sorted) {
    for (const f of r.findings) {
      if ((f.severity || "").toLowerCase() !== "blocker") continue;
      tbody.insertAdjacentHTML("beforeend", `
        <tr>
          <td>${r.project}</td>
          <td>${r.feature}</td>
          <td>${r.stage}</td>
          <td>${escapeHtml(f.title || "")}</td>
          <td>${(f.personas || []).join(", ")}</td>
        </tr>`);
      count++;
      if (count >= 30) return;
    }
  }
  if (!count) {
    tbody.insertAdjacentHTML("beforeend",
      `<tr><td colspan="5" class="empty">No blocker-severity findings recorded.</td></tr>`);
  }
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatJudgeTs(ts) {
  try {
    const d = new Date(ts);
    if (isNaN(d.getTime())) return ts;
    const mm = String(d.getMonth() + 1).padStart(2, "0");
    const dd = String(d.getDate()).padStart(2, "0");
    const hh = String(d.getHours()).padStart(2, "0");
    const mi = String(d.getMinutes()).padStart(2, "0");
    return `${mm}/${dd} ${hh}:${mi}`;
  } catch {
    return ts;
  }
}

// Public entry — called by index.html when the user toggles to Judge mode.
window.__renderJudgeView = function () {
  if (!judgeState.loaded) {
    if (!loadJudgeBundle()) {
      document.getElementById("main").innerHTML =
        `<div class="card wide"><div class="empty">
          judge-bundle.js not found. Run:
          <code>bash ~/Projects/MonsterFlow/scripts/judge-dashboard-bundle.sh</code>
        </div></div>`;
      document.getElementById("tabs").innerHTML = "";
      return;
    }
  }
  renderJudgeTabs();
  renderJudgeMain();
  document.getElementById("last-updated").textContent =
    judgeState.generatedAt
      ? `judge bundle: ${judgeState.generatedAt}`
      : "no judge data yet";
};
