#!/usr/bin/env python3
"""Persona roster sidecar emitter — Wave 1 task 1.7 (token-economics).

Walks ~/.claude/personas/{review,plan,check}/*.md and emits
dashboard/data/persona-roster.js for the dashboard's hybrid render under
file:// (no fetch — must be loaded via <script src>).

Gate mapping (CRITICAL):
    personas/review/  -> gate "spec-review"  (review personas run AT the spec-review GATE)
    personas/plan/    -> gate "plan"
    personas/check/   -> gate "check"

Skipped:
    - judge.md, synthesis.md (not gate personas)
    - code-review/*.md (separate review surface, not a gate)
    - *.bak files
    - dotfiles (names starting with ".")

Atomic write via tmp + os.replace. Idempotent: safe to re-run; output is
gitignored under dashboard/data/.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import os
import sys
import tempfile
import unicodedata
from pathlib import Path

# Persona directory name -> gate name (gate name is what gets persisted).
_DIR_TO_GATE = {
    "review": "spec-review",
    "plan": "plan",
    "check": "check",
}

# Filenames inside a gate dir that are NOT gate personas.
_NON_PERSONA_FILES = {"judge.md", "synthesis.md"}


def compute_persona_content_hash(file_path: Path) -> str:
    """Read file, NFC-normalize, normalize line endings to \\n, return sha256:HEX."""
    raw = file_path.read_text(encoding="utf-8")
    normalized = unicodedata.normalize("NFC", raw)
    # Normalize CRLF and lone CR to LF.
    normalized = normalized.replace("\r\n", "\n").replace("\r", "\n")
    digest = hashlib.sha256(normalized.encode("utf-8")).hexdigest()
    return f"sha256:{digest}"


def _iso_utc_from_mtime(mtime: float) -> str:
    """Convert POSIX mtime to ISO-8601 UTC with 'Z' suffix."""
    dt = _dt.datetime.fromtimestamp(mtime, tz=_dt.timezone.utc)
    # Preserve microsecond precision if present; trim trailing zeros for cleanliness.
    return dt.strftime("%Y-%m-%dT%H:%M:%S") + ("." + f"{dt.microsecond:06d}" if dt.microsecond else "") + "Z"


def _iso_utc_now() -> str:
    return _dt.datetime.now(tz=_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def walk_roster(personas_root: Path | None = None) -> list[dict]:
    """Walk personas_root/{review,plan,check}/*.md and return a list of roster rows.

    Rows are sorted by (gate, persona) for byte-stable diffs.
    """
    if personas_root is None:
        personas_root = Path.home() / ".claude" / "personas"

    rows: list[dict] = []

    for dir_name, gate in _DIR_TO_GATE.items():
        gate_dir = personas_root / dir_name
        if not gate_dir.is_dir():
            continue
        for entry in sorted(gate_dir.iterdir()):
            name = entry.name
            if not entry.is_file():
                continue
            if name.startswith("."):
                continue
            if not name.endswith(".md"):
                continue
            # Skip backup files (e.g. foo.md.bak — already filtered by .md
            # suffix, but be explicit in case of foo.bak.md edge cases).
            if name.endswith(".bak") or ".bak." in name:
                continue
            if name in _NON_PERSONA_FILES:
                continue

            persona = name[:-3]  # strip .md
            stat = entry.stat()
            row = {
                "persona": persona,
                "gate": gate,
                # file_path is repo-relative-style, mirroring data-model sketch.
                "file_path": f"personas/{dir_name}/{name}",
                "persona_content_hash": compute_persona_content_hash(entry),
                "last_modified": _iso_utc_from_mtime(stat.st_mtime),
                "deprecated": False,
            }
            rows.append(row)

    rows.sort(key=lambda r: (r["gate"], r["persona"]))
    return rows


def emit_roster_sidecar(rows: list[dict], output_path: Path) -> None:
    """Atomically write the JS sidecar to output_path."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    generated_at = _iso_utc_now()
    body_lines = [
        "// AUTOGENERATED by scripts/compute-persona-value.py — do not edit.",
        "// Loaded via <script src> under file:// (no fetch).",
        "window.PERSONA_ROSTER = "
        + json.dumps(rows, indent=2, sort_keys=True, ensure_ascii=False)
        + ";",
        f'window.PERSONA_ROSTER_GENERATED_AT = "{generated_at}";',
        "",
    ]
    body = "\n".join(body_lines)

    # Atomic write: tmp file in same dir, then os.replace.
    fd, tmp_path = tempfile.mkstemp(
        prefix=".persona-roster.",
        suffix=".js.tmp",
        dir=str(output_path.parent),
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(body)
        os.replace(tmp_path, output_path)
    except Exception:
        # Best-effort cleanup if replace failed.
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


def _main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Emit dashboard/data/persona-roster.js sidecar.",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output path for the JS sidecar (e.g. dashboard/data/persona-roster.js).",
    )
    parser.add_argument(
        "--personas-root",
        default=None,
        help="Override personas root (default: ~/.claude/personas).",
    )
    args = parser.parse_args(argv)

    personas_root = Path(args.personas_root).expanduser() if args.personas_root else None
    rows = walk_roster(personas_root)
    output_path = Path(args.output).expanduser()
    emit_roster_sidecar(rows, output_path)
    print(
        f"emitted {len(rows)} roster rows to {output_path}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(_main(sys.argv[1:]))
