#!/usr/bin/env bash
# dashboard-bundle.sh — rebuild dashboard/data-bundle.js from all JSONL files.
# Called by dashboard-append.sh after each append so the dashboard works from
# file:// without a local server (script tags bypass CORS; fetch() does not).

set -euo pipefail

WORKFLOW_ROOT="$HOME/Projects/claude-workflow"
DATA_DIR="$WORKFLOW_ROOT/dashboard/data"
OUT="$WORKFLOW_ROOT/dashboard/data-bundle.js"

python3 - "$DATA_DIR" "$OUT" <<'PY'
import json, os, sys, pathlib, glob

data_dir, out = sys.argv[1], sys.argv[2]
bundle = {}
for path in sorted(glob.glob(os.path.join(data_dir, "*.jsonl"))):
    slug = pathlib.Path(path).stem
    records = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                records.append(json.loads(line))
            except Exception:
                continue
    if records:
        bundle[slug] = records

payload = json.dumps(bundle, indent=2)
with open(out, "w") as f:
    f.write("// Auto-generated by scripts/dashboard-bundle.sh — do not edit.\n")
    f.write(f"window.__GRAPHIFY_DATA = {payload};\n")
print(f"bundled {len(bundle)} projects into {out}")
PY
